/**
 * Catalogue content mirrors the services and product lines Renderways
 * Technology actually offers (Maduravoyal, Chennai · Katpadi, Vellore).
 */

export const services = [
  {
    title: 'Computer Sales',
    slug: 'computer-sales',
    shortDescription:
      'Brand-new and refurbished desktops configured for home, office, gaming and billing counters.',
    description:
      'We build and supply desktops tuned to how you actually work — from lean billing machines for retail counters to multi-core workstations for design and CAD. Every unit ships pre-loaded with a licensed OS, essential drivers and a health check, with on-site delivery across Chennai and Vellore.',
    icon: 'Monitor',
    features: [
      'Custom builds — Intel & AMD',
      'Branded desktops: HP, Dell, Lenovo, Acer',
      'Refurbished units from ₹9,999',
      'Free OS setup + data migration',
      'On-site delivery & installation',
    ],
    startingPrice: 9999,
    priceNote: 'onwards',
    ticketCategory: 'spare-parts',
    turnaround: 'Same-day delivery in Chennai',
    isFeatured: true,
    order: 1,
  },
  {
    title: 'Laptop & Accessories',
    slug: 'laptop-accessories-sales',
    shortDescription:
      'Laptops, chargers, batteries, docking stations and every accessory in between — sold and serviced.',
    description:
      'Whether you need a fleet of business laptops or a single replacement keyboard, we stock it. All accessories are genuine or OEM-grade, and we test every unit before it leaves the counter.',
    icon: 'Laptop',
    features: [
      'Business, student & gaming laptops',
      'Genuine batteries, adapters, keyboards',
      'SSD & RAM upgrades while you wait',
      'Bulk & corporate pricing',
      'Trade-in on your old device',
    ],
    startingPrice: 14999,
    priceNote: 'onwards',
    ticketCategory: 'laptop-repair',
    turnaround: 'In stock — walk in and collect',
    isFeatured: true,
    order: 2,
  },
  {
    title: 'Chip-Level Service',
    slug: 'chip-level-service',
    shortDescription:
      'Micro-soldering repairs on laptop and desktop motherboards — the fix most service centres refuse.',
    description:
      'Dead board? No display? Liquid damage? Our chip-level bench handles BGA rework, IC replacement, power-section rebuilds and track repairs under a microscope. We diagnose down to the component instead of selling you a whole new motherboard.',
    icon: 'Cpu',
    features: [
      'BGA reballing & chip replacement',
      'No-power / no-display diagnosis',
      'Liquid damage recovery',
      'Charging IC & power section repair',
      'Free diagnosis — pay only if repaired',
    ],
    startingPrice: 1500,
    priceNote: 'after free diagnosis',
    ticketCategory: 'chip-level-service',
    turnaround: '2–4 working days',
    isFeatured: true,
    order: 3,
  },
  {
    title: 'Board-Level Service',
    slug: 'board-level-service',
    shortDescription:
      'Fast component and module-level repairs for motherboards, SMPS, display panels and more.',
    description:
      'For faults that do not need a microscope, our board-level bench swaps failed modules, capacitors and connectors the same day — keeping your machine out of the scrap heap and your downtime to hours instead of weeks.',
    icon: 'CircuitBoard',
    features: [
      'Motherboard & SMPS repair',
      'Display panel and hinge replacement',
      'Port, jack & connector rebuilds',
      'Capacitor and MOSFET replacement',
      '30-day warranty on every repair',
    ],
    startingPrice: 800,
    priceNote: 'after free diagnosis',
    ticketCategory: 'board-level-service',
    turnaround: '24–48 hours',
    isFeatured: false,
    order: 4,
  },
  {
    title: 'Computer Spare Parts',
    slug: 'computer-spare-parts',
    shortDescription:
      'Genuine RAM, SSDs, SMPS, panels, keyboards, fans and cabinets — in stock, not "order and wait".',
    description:
      'We keep a deep local inventory so your repair is not held hostage by a two-week courier. Retail and wholesale rates available for service partners across Tamil Nadu.',
    icon: 'HardDrive',
    features: [
      'RAM, SSD, HDD, NVMe',
      'SMPS, cabinets, cooling fans',
      'Laptop panels, keyboards, hinges',
      'Genuine & OEM parts only',
      'Wholesale rates for partners',
    ],
    startingPrice: 350,
    priceNote: 'onwards',
    ticketCategory: 'spare-parts',
    turnaround: 'Over the counter',
    isFeatured: false,
    order: 5,
  },
  {
    title: 'Hard Disk Data Recovery',
    slug: 'hard-disk-data-recovery',
    shortDescription:
      'Clicking, dead, formatted or corrupted drives — we recover what everyone else declared lost.',
    description:
      'Photos, accounts, project files, Tally data. We handle logical corruption, deleted partitions, firmware faults and mechanical failures, with a strict no-recovery-no-fee policy and complete confidentiality.',
    icon: 'DatabaseBackup',
    features: [
      'HDD, SSD, pen drive & memory cards',
      'Formatted & deleted partition recovery',
      'RAID and server volume recovery',
      'No recovery, no fee',
      '100% confidential handling',
    ],
    startingPrice: 2500,
    priceNote: 'depends on drive condition',
    ticketCategory: 'data-recovery',
    turnaround: '2–7 days',
    isFeatured: true,
    order: 6,
  },
  {
    title: 'CCTV Installation',
    slug: 'cctv-installation',
    shortDescription:
      'End-to-end surveillance setup for homes, shops, factories and apartments — with mobile viewing.',
    description:
      'Free site survey, camera placement planning, concealed cabling, DVR/NVR configuration and mobile app setup. We install so that every blind spot is covered and you can watch the feed from anywhere.',
    icon: 'Cctv',
    features: [
      'Free on-site survey & quotation',
      'HD, 4K, IP and Wi-Fi cameras',
      'Mobile + desktop live viewing',
      'Night vision & motion alerts',
      'Concealed, weatherproof cabling',
    ],
    startingPrice: 12000,
    priceNote: '4-camera setup onwards',
    ticketCategory: 'cctv-installation',
    turnaround: 'Installed within 48 hours',
    isFeatured: true,
    order: 7,
  },
  {
    title: 'CCTV Sales & Service',
    slug: 'cctv-sales-service',
    shortDescription:
      'Cameras, DVRs, NVRs and storage from Hikvision, CP Plus and Dahua — plus AMC for existing systems.',
    description:
      'Already have cameras that stopped recording? We service every major brand, replace failed units, recover DVR footage and take over annual maintenance for systems we did not install.',
    icon: 'Video',
    features: [
      'Hikvision · CP Plus · Dahua · Godrej',
      'DVR/NVR repair & footage recovery',
      'Camera repositioning & upgrades',
      'Annual maintenance contracts',
      'Emergency same-day call-out',
    ],
    startingPrice: 1800,
    priceNote: 'per camera onwards',
    ticketCategory: 'cctv-service',
    turnaround: 'Same-day for AMC clients',
    isFeatured: false,
    order: 8,
  },
  {
    title: 'IT Peripheral Rentals',
    slug: 'it-peripheral-rentals',
    shortDescription:
      'Laptops, desktops, projectors and printers on rent — daily, monthly or for the length of a project.',
    description:
      'Scaling a team, running a training batch or hosting an event? Rent tested, ready-to-use hardware with delivery, setup and swap-out support included. Ideal for startups, exam centres and short-term project teams.',
    icon: 'PackageOpen',
    features: [
      'Laptops & desktops from ₹399/day',
      'Projectors, printers & monitors',
      'Daily, weekly, monthly plans',
      'Free delivery, setup & pickup',
      'Instant replacement on failure',
    ],
    startingPrice: 399,
    priceNote: 'per day',
    ticketCategory: 'rental',
    turnaround: 'Delivered same day',
    isFeatured: false,
    order: 9,
  },
  {
    title: 'Residential & Commercial AMC',
    slug: 'residential-commercial-amc',
    shortDescription:
      'Annual maintenance for homes, offices and shops — unlimited call-outs, one predictable fee.',
    description:
      'Stop paying per visit. Our AMC covers preventive servicing, priority response, remote support and unlimited on-site call-outs across your whole fleet of machines and cameras.',
    icon: 'ShieldCheck',
    features: [
      'Unlimited on-site visits',
      'Priority 4-hour response',
      'Quarterly preventive servicing',
      'Free remote support',
      'Discounted spare parts',
    ],
    startingPrice: 4999,
    priceNote: 'per year',
    ticketCategory: 'amc',
    turnaround: 'Priority 4-hour response',
    isFeatured: false,
    order: 10,
  },
  {
    title: 'Networking & Wi-Fi Setup',
    slug: 'networking-wifi-setup',
    shortDescription:
      'Structured cabling, routers, switches and dead-zone-free Wi-Fi for offices and homes.',
    description:
      'From a single router to a full office LAN — we plan, cable, configure and secure your network, including guest Wi-Fi, static IP setup and network-attached storage.',
    icon: 'Network',
    features: [
      'LAN & structured cabling',
      'Router, switch & firewall setup',
      'Mesh Wi-Fi for full coverage',
      'NAS & shared drive configuration',
      'Network security hardening',
    ],
    startingPrice: 2500,
    priceNote: 'onwards',
    ticketCategory: 'networking',
    turnaround: '1–3 days',
    isFeatured: false,
    order: 11,
  },
];

export const products = [
  {
    name: 'Renderways Office Pro Desktop (i5 12th Gen)',
    slug: 'renderways-office-pro-i5-12th-gen',
    category: 'desktop',
    brand: 'Renderways',
    shortDescription: 'Custom-built i5 desktop for offices, billing counters and everyday work.',
    specs: [
      { label: 'Processor', value: 'Intel Core i5-12400' },
      { label: 'RAM', value: '16 GB DDR4' },
      { label: 'Storage', value: '512 GB NVMe SSD' },
      { label: 'Monitor', value: '21.5" Full HD IPS' },
      { label: 'OS', value: 'Windows 11 Pro' },
    ],
    price: 42999,
    mrp: 49999,
    warrantyMonths: 12,
    stockCount: 8,
    isFeatured: true,
  },
  {
    name: 'Renderways Creator Workstation (i7 + RTX 4060)',
    slug: 'renderways-creator-workstation-i7-rtx4060',
    category: 'desktop',
    brand: 'Renderways',
    shortDescription: 'Rendering, editing and CAD workstation built for sustained heavy loads.',
    specs: [
      { label: 'Processor', value: 'Intel Core i7-13700' },
      { label: 'Graphics', value: 'NVIDIA RTX 4060 8 GB' },
      { label: 'RAM', value: '32 GB DDR5' },
      { label: 'Storage', value: '1 TB NVMe + 2 TB HDD' },
      { label: 'Cooling', value: '240mm liquid cooler' },
    ],
    price: 114999,
    mrp: 129999,
    warrantyMonths: 24,
    stockCount: 3,
    isFeatured: true,
  },
  {
    name: 'Dell Latitude 3540 Business Laptop',
    slug: 'dell-latitude-3540-business-laptop',
    category: 'laptop',
    brand: 'Dell',
    shortDescription: 'Reliable 15.6" business laptop with full-day battery and TPM security.',
    specs: [
      { label: 'Processor', value: 'Intel Core i5-1335U' },
      { label: 'RAM', value: '16 GB DDR4' },
      { label: 'Storage', value: '512 GB SSD' },
      { label: 'Display', value: '15.6" FHD anti-glare' },
    ],
    price: 58999,
    mrp: 66999,
    warrantyMonths: 12,
    stockCount: 6,
    isFeatured: true,
  },
  {
    name: 'HP 250 G9 Laptop (Refurbished · Grade A)',
    slug: 'hp-250-g9-refurbished-grade-a',
    category: 'laptop',
    brand: 'HP',
    shortDescription: 'Certified refurbished, fully tested, with a fresh SSD and 6-month warranty.',
    condition: 'refurbished',
    specs: [
      { label: 'Processor', value: 'Intel Core i3-1215U' },
      { label: 'RAM', value: '8 GB DDR4' },
      { label: 'Storage', value: '256 GB SSD (new)' },
      { label: 'Grade', value: 'A — minimal cosmetic wear' },
    ],
    price: 24999,
    mrp: 34999,
    warrantyMonths: 6,
    stockCount: 11,
  },
  {
    name: 'Hikvision 4-Camera 2MP CCTV Kit',
    slug: 'hikvision-4-camera-2mp-cctv-kit',
    category: 'cctv',
    brand: 'Hikvision',
    shortDescription: 'Complete 4-camera kit with DVR, 1 TB storage, cabling and installation.',
    specs: [
      { label: 'Cameras', value: '4 × 2MP HD (2 dome, 2 bullet)' },
      { label: 'Recorder', value: '4-channel DVR' },
      { label: 'Storage', value: '1 TB surveillance HDD' },
      { label: 'Night vision', value: 'Up to 20 metres' },
      { label: 'Includes', value: 'Cabling, power supply, installation' },
    ],
    price: 18999,
    mrp: 23999,
    warrantyMonths: 24,
    stockCount: 14,
    isFeatured: true,
  },
  {
    name: 'CP Plus 8-Camera 5MP IP Surveillance Kit',
    slug: 'cp-plus-8-camera-5mp-ip-kit',
    category: 'cctv',
    brand: 'CP Plus',
    shortDescription: 'High-resolution 8-camera IP system for showrooms, factories and warehouses.',
    specs: [
      { label: 'Cameras', value: '8 × 5MP IP colour night vision' },
      { label: 'Recorder', value: '8-channel NVR with PoE' },
      { label: 'Storage', value: '2 TB surveillance HDD' },
      { label: 'Features', value: 'Motion alerts, mobile app, two-way audio' },
    ],
    price: 54999,
    mrp: 67999,
    warrantyMonths: 24,
    stockCount: 5,
    isFeatured: true,
  },
  {
    name: 'Crucial 1TB NVMe Gen4 SSD',
    slug: 'crucial-1tb-nvme-gen4-ssd',
    category: 'storage',
    brand: 'Crucial',
    shortDescription: 'Drop-in upgrade that makes an ageing laptop feel new — free fitting in store.',
    specs: [
      { label: 'Capacity', value: '1 TB' },
      { label: 'Interface', value: 'PCIe Gen4 NVMe M.2' },
      { label: 'Read speed', value: 'Up to 5,000 MB/s' },
    ],
    price: 6499,
    mrp: 8299,
    warrantyMonths: 60,
    stockCount: 22,
    isFeatured: true,
  },
  {
    name: 'Seagate 2TB Desktop Hard Drive',
    slug: 'seagate-2tb-desktop-hard-drive',
    category: 'storage',
    brand: 'Seagate',
    shortDescription: 'Bulk storage for backups, CCTV recording and media archives.',
    specs: [
      { label: 'Capacity', value: '2 TB' },
      { label: 'Interface', value: 'SATA III 3.5"' },
      { label: 'Speed', value: '7200 RPM' },
    ],
    price: 4699,
    mrp: 5999,
    warrantyMonths: 24,
    stockCount: 18,
  },
  {
    name: 'Corsair Vengeance 16GB DDR4 RAM',
    slug: 'corsair-vengeance-16gb-ddr4',
    category: 'spare-parts',
    brand: 'Corsair',
    shortDescription: 'Memory upgrade kit with lifetime warranty and free installation.',
    specs: [
      { label: 'Capacity', value: '16 GB (2 × 8 GB)' },
      { label: 'Speed', value: '3200 MHz' },
      { label: 'Type', value: 'DDR4 DIMM' },
    ],
    price: 3899,
    mrp: 5199,
    warrantyMonths: 120,
    stockCount: 25,
  },
  {
    name: 'Antec 550W 80+ Bronze SMPS',
    slug: 'antec-550w-80-plus-bronze-smps',
    category: 'spare-parts',
    brand: 'Antec',
    shortDescription: 'Stable, protected power supply — the most common cause of "dead" desktops.',
    specs: [
      { label: 'Wattage', value: '550W' },
      { label: 'Efficiency', value: '80+ Bronze' },
      { label: 'Protection', value: 'OVP, UVP, SCP, OPP' },
    ],
    price: 3299,
    mrp: 4299,
    warrantyMonths: 36,
    stockCount: 2,
  },
  {
    name: 'TP-Link Archer AX53 Wi-Fi 6 Router',
    slug: 'tp-link-archer-ax53-wifi-6-router',
    category: 'networking',
    brand: 'TP-Link',
    shortDescription: 'Wi-Fi 6 coverage for homes and small offices, configured free of charge.',
    specs: [
      { label: 'Standard', value: 'Wi-Fi 6 (AX3000)' },
      { label: 'Speed', value: '2402 Mbps + 574 Mbps' },
      { label: 'Ports', value: '4 × Gigabit LAN' },
    ],
    price: 5499,
    mrp: 6999,
    warrantyMonths: 36,
    stockCount: 9,
  },
  {
    name: 'Logitech MK270 Wireless Keyboard & Mouse',
    slug: 'logitech-mk270-wireless-combo',
    category: 'accessories',
    brand: 'Logitech',
    shortDescription: 'Reliable wireless combo with long battery life — the office standard.',
    specs: [
      { label: 'Connection', value: '2.4 GHz wireless' },
      { label: 'Battery', value: 'Up to 24 months (keyboard)' },
    ],
    price: 1599,
    mrp: 2295,
    warrantyMonths: 36,
    stockCount: 40,
  },
  {
    name: 'Business Laptop on Rent (i5 · 8GB · SSD)',
    slug: 'business-laptop-on-rent-i5',
    category: 'rental',
    brand: 'Renderways',
    shortDescription: 'Ready-to-work laptop delivered to your desk — daily and monthly plans.',
    specs: [
      { label: 'Processor', value: 'Intel Core i5' },
      { label: 'RAM', value: '8 GB' },
      { label: 'Storage', value: '256 GB SSD' },
      { label: 'Includes', value: 'Windows, Office, antivirus, charger bag' },
    ],
    price: 0,
    rentalPricePerDay: 399,
    stockCount: 30,
    isFeatured: true,
  },
  {
    name: 'Full HD Projector on Rent',
    slug: 'full-hd-projector-on-rent',
    category: 'rental',
    brand: 'Epson',
    shortDescription: 'Event and training-ready projector with screen, cables and on-site setup.',
    specs: [
      { label: 'Resolution', value: '1920 × 1080 Full HD' },
      { label: 'Brightness', value: '3600 lumens' },
      { label: 'Includes', value: 'Screen, HDMI cable, setup' },
    ],
    price: 0,
    rentalPricePerDay: 899,
    stockCount: 6,
  },
];

export const demoUsers = [
  {
    name: 'Renderways Admin',
    email: 'admin@renderways.in',
    phone: '+917358189215',
    password: 'admin123',
    role: 'admin',
    company: 'Renderways Technology',
  },
  {
    name: 'Bala Murugan',
    email: 'bala@renderways.in',
    phone: '9543095480',
    password: 'tech123',
    role: 'technician',
    skills: ['Chip-level service', 'Laptop repair', 'Data recovery'],
  },
  {
    name: 'Karthik Raja',
    email: 'karthik@renderways.in',
    phone: '8189880681',
    password: 'tech123',
    role: 'technician',
    skills: ['CCTV installation', 'Networking', 'Board-level service'],
  },
  {
    name: 'Priya Dharshini',
    email: 'priya@renderways.in',
    phone: '9008180476',
    password: 'tech123',
    role: 'technician',
    skills: ['Desktop repair', 'OS & software', 'Preventive AMC'],
  },
  {
    name: 'Sumaiya Zara',
    email: 'sumaiya@example.com',
    phone: '9876543210',
    password: 'demo123',
    role: 'customer',
    company: 'Zara Textiles',
    address: { line1: '12 Anna Nagar Main Road', city: 'Chennai', pincode: '600040' },
  },
  {
    name: 'Alex Simon',
    email: 'alex@example.com',
    phone: '9840012345',
    password: 'demo123',
    role: 'customer',
    company: 'Simon Traders',
    address: { line1: '45 Poonamallee High Road', city: 'Chennai', pincode: '600056' },
  },
  {
    name: 'Ramesh Kumar',
    email: 'ramesh@example.com',
    phone: '9791234567',
    password: 'demo123',
    role: 'customer',
    company: 'RK Auto Spares',
    address: { line1: '8 Gandhi Street, Katpadi', city: 'Vellore', pincode: '632006' },
  },
];

/**
 * Sample tickets across every stage of the workflow, so the dashboards,
 * charts and SLA badges have realistic data on a fresh install.
 * `daysAgo` backdates the ticket; `rating` is only applied to closed ones.
 */
export const demoTickets = [
  {
    customerEmail: 'sumaiya@example.com',
    technicianEmail: 'bala@renderways.in',
    subject: 'Laptop not powering on after voltage fluctuation',
    description:
      'HP Pavilion laptop suddenly stopped turning on after a power cut at the shop. No lights, no fan. Charger is working fine on another laptop. Need this urgently, all our billing data is on it.',
    category: 'chip-level-service',
    priority: 'urgent',
    status: 'closed',
    serviceMode: 'carry-in',
    device: { type: 'Laptop', brand: 'HP', model: 'Pavilion 15', underWarranty: false },
    estimatedCost: 3500,
    finalCost: 3200,
    resolutionSummary:
      'Charging IC and one shorted MOSFET on the power section were replaced. Board tested for 6 hours under load — stable. Data intact, no reinstall required.',
    daysAgo: 22,
    rating: {
      stars: 5,
      feedback:
        'Nice service from the service person Bala Murugan. Thanks for your quick response — got the laptop back in two days with all my data safe.',
    },
  },
  {
    customerEmail: 'alex@example.com',
    technicianEmail: 'karthik@renderways.in',
    subject: 'CCTV installation for new warehouse — 8 cameras',
    description:
      'We have taken a new warehouse in Ambattur, around 4000 sq ft. Need full CCTV coverage including entrance, loading bay and office cabin. Would like mobile viewing for two people.',
    category: 'cctv-installation',
    priority: 'high',
    status: 'closed',
    serviceMode: 'onsite',
    location: { line1: 'Plot 22, Ambattur Industrial Estate', city: 'Chennai', pincode: '600058' },
    estimatedCost: 56000,
    finalCost: 54999,
    resolutionSummary:
      '8 × 5MP IP cameras installed with PoE NVR and 2 TB storage. Concealed conduit cabling throughout. Mobile app configured on three devices, motion alerts enabled for after-hours.',
    daysAgo: 15,
    rating: {
      stars: 5,
      feedback:
        'Very kind and effective service. Was very quick in resolving my case — the team finished the whole warehouse in a single day and the app setup works perfectly.',
    },
  },
  {
    customerEmail: 'ramesh@example.com',
    technicianEmail: 'bala@renderways.in',
    subject: 'External hard disk clicking — need Tally data recovered',
    description:
      'My 1TB Seagate external drive started making a clicking sound and is not detected on any computer. It has 6 years of Tally backups. Please recover if possible.',
    category: 'data-recovery',
    priority: 'urgent',
    status: 'resolved',
    serviceMode: 'carry-in',
    device: { type: 'External HDD', brand: 'Seagate', model: 'Expansion 1TB' },
    estimatedCost: 8000,
    finalCost: 7500,
    resolutionSummary:
      'Head stack assembly was faulty. Donor drive sourced and swapped in a clean environment. 97% of data recovered including the complete Tally folder. Delivered on a new SSD.',
    daysAgo: 4,
  },
  {
    customerEmail: 'sumaiya@example.com',
    technicianEmail: 'priya@renderways.in',
    subject: 'Billing computer very slow, hangs during peak hours',
    description:
      'Our shop billing desktop takes almost 5 minutes to boot and freezes when we open Tally along with the browser. It was fine until about two months back.',
    category: 'computer-repair',
    priority: 'medium',
    status: 'in_progress',
    serviceMode: 'onsite',
    device: { type: 'Desktop', brand: 'Assembled', model: 'i3 8th Gen' },
    estimatedCost: 6500,
    daysAgo: 2,
  },
  {
    customerEmail: 'alex@example.com',
    technicianEmail: 'karthik@renderways.in',
    subject: 'Office Wi-Fi dead zones in the back cabins',
    description:
      'Single router in reception does not reach the last two cabins. Around 15 staff affected during video calls. Office is roughly 2200 sq ft on one floor.',
    category: 'networking',
    priority: 'medium',
    status: 'assigned',
    serviceMode: 'onsite',
    location: { line1: '45 Poonamallee High Road', city: 'Chennai', pincode: '600056' },
    daysAgo: 1,
  },
  {
    customerEmail: 'ramesh@example.com',
    subject: 'Need 5 laptops on rent for a 3-month audit project',
    description:
      'Auditors joining from next Monday for three months. Need 5 laptops with Office and antivirus, delivered to our Vellore office. Please share monthly rental quote.',
    category: 'rental',
    priority: 'high',
    status: 'open',
    serviceMode: 'onsite',
    location: { line1: '8 Gandhi Street, Katpadi', city: 'Vellore', pincode: '632006' },
    daysAgo: 0,
  },
  {
    customerEmail: 'sumaiya@example.com',
    subject: 'CCTV DVR not recording for the last 3 days',
    description:
      'Cameras show live feed on the monitor but nothing is being recorded. Cannot play back any footage from this week. System was installed two years ago.',
    category: 'cctv-service',
    priority: 'high',
    status: 'open',
    serviceMode: 'onsite',
    location: { line1: '12 Anna Nagar Main Road', city: 'Chennai', pincode: '600040' },
    daysAgo: 0,
  },
  {
    customerEmail: 'alex@example.com',
    technicianEmail: 'priya@renderways.in',
    subject: 'Annual maintenance renewal for 12 office systems',
    description:
      'Our AMC expires at the end of this month. Please renew for 12 desktops and 2 printers, and schedule the quarterly preventive service.',
    category: 'amc',
    priority: 'low',
    status: 'awaiting_customer',
    serviceMode: 'onsite',
    estimatedCost: 24999,
    daysAgo: 6,
  },
];
